import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
	node_env: process.env.NODE_ENV,
	port: process.env.PORT,
	database_url: process.env.DATABASE_URL,
	bak_url: process.env.APP_URL,
	frontend_url: process.env.FRONTEND_URL,
	bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
	jwt_access_secret: process.env.JWT_ACCESS_SECRET as string,
	jwt_refresh_secret: process.env.JWT_REFRESH_SECRET as string,
	jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN,
	jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN,
	google_client_id: process.env.GOOGLE_CLIENT_ID,
	super_admin_name: process.env.SUPER_ADMIN_NAME,
	super_admin_email: process.env.SUPER_ADMIN_EMAIL,
	super_admin_password: process.env.SUPER_ADMIN_PASSWORD,
	admin_name: process.env.ADMIN_NAME || process.env.SUPER_ADMIN_NAME,
	admin_email: process.env.ADMIN_EMAIL || process.env.SUPER_ADMIN_EMAIL,
	admin_password:
		process.env.ADMIN_PASSWORD || process.env.SUPER_ADMIN_PASSWORD,
	admin_phone: process.env.ADMIN_PHONE,
	operations_manager_name: process.env.OPERATIONS_MANAGER_NAME,
	operations_manager_email: process.env.OPERATIONS_MANAGER_EMAIL,
	operations_manager_password: process.env.OPERATIONS_MANAGER_PASSWORD,
	operations_manager_phone: process.env.OPERATIONS_MANAGER_PHONE,
	hub_manager_name: process.env.HUB_MANAGER_NAME,
	hub_manager_email: process.env.HUB_MANAGER_EMAIL,
	hub_manager_password: process.env.HUB_MANAGER_PASSWORD,
	hub_manager_phone: process.env.HUB_MANAGER_PHONE,
	courier_name: process.env.COURIER_NAME,
	courier_email: process.env.COURIER_EMAIL,
	courier_password: process.env.COURIER_PASSWORD,
	courier_phone: process.env.COURIER_PHONE,
	tester_admin_name: process.env.TESTER_ADMIN_NAME,
	tester_admin_email: process.env.TESTER_ADMIN_EMAIL,
	tester_admin_password: process.env.TESTER_ADMIN_PASSWORD,
	tester_doctor_name: process.env.TESTER_DOCTOR_NAME,
	tester_doctor_email: process.env.TESTER_DOCTOR_EMAIL,
	tester_doctor_password: process.env.TESTER_DOCTOR_PASSWORD,
	redis_user: process.env.REDIS_USER,
	redis_password: process.env.REDIS_PASSWORD,
	redis_host: process.env.REDIS_HOST,
	redis_port: process.env.REDIS_PORT,
	smtp_user: process.env.SMTP_USER,
	smtp_password: process.env.SMTP_PASSWORD,
	email_sender: process.env.EMAIL_SENDER,
	cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
	cloudinary_api_key: process.env.CLOUDINARY_API_KEY,
	cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET,
	bkash_base_url: process.env.BKASH_BASE_URL,
	bkash_username: process.env.BKASH_USERNAME,
	bkash_password: process.env.BKASH_PASSWORD,
	bkash_app_key: process.env.BKASH_APP_KEY,
	bkash_app_secret: process.env.BKASH_APP_SECRET,
	bkash_callback_url: process.env.BKASH_CALLBACK_URL,
	stripe_secret_key: process.env.STRIPE_SECRET_KEY,
	stripe_publishable_key: process.env.STRIPE_PUBLISHABLE_KEY,
	stripe_webhook_secret: process.env.STRIPE_WEBHOOK_SECRET,
	stripe_currency: process.env.STRIPE_CURRENCY || "bdt",
};
